// js/data.js
const TOOLS = [
    {
      id: "webflow",
      name: "Webflow",
      category: "Website Builder",
      short_description: "Visual website builder with CMS and pixel-level control.",
      long_description: "Webflow is a designer-first visual builder that produces clean HTML/CSS, and includes CMS and hosting. It suits marketing sites and landing pages that need precise animations.",
      tags: ["no-code","cms","design-driven"],
      skill_level: "intermediate",
      pricing_model: "paid",
      starts_at: "$12/month",
      integrations: ["Zapier","Google Analytics"],
      pros: ["Precise layout control","Built-in CMS","Clean code export"],
      cons: ["Subscription cost","Learning curve for advanced interactions"],
      official_url: "https://webflow.com",
      case_studies: [{title:"Startup landing", summary:"Launched marketing site quickly.", link:"https://webflow.com"}],
      last_updated: "2025-11-11"
    },
    {
      id: "wix",
      name: "Wix",
      category: "Website Builder",
      short_description: "Drag-and-drop builder for beginners with many templates.",
      long_description: "Wix focuses on ease-of-use, allowing non-technical users to launch websites quickly using AI and templates.",
      tags: ["no-code","templates","ecommerce"],
      skill_level: "beginner",
      pricing_model: "freemium",
      starts_at: "Free / Paid plans",
      integrations: ["Stripe","Wix Stores"],
      pros: ["Very easy to use","Fast setup"],
      cons: ["Limited advanced customization","Proprietary hosting"],
      official_url: "https://wix.com",
      case_studies: [{title:"Local business", summary:"Bakery site with online ordering.", link:"#"}],
      last_updated: "2025-11-11"
    },
    {
      id: "wordpress",
      name: "WordPress + Elementor",
      category: "CMS / Page Builder",
      short_description: "Powerful CMS; Elementor adds visual page building.",
      long_description: "WordPress is the most popular CMS with a large plugin ecosystem; Elementor enables drag-and-drop page building for non-coders.",
      tags: ["cms","plugins","ecommerce"],
      skill_level: "intermediate",
      pricing_model: "freemium",
      starts_at: "Free / Hosting cost",
      integrations: ["WooCommerce","Yoast"],
      pros: ["Highly extensible","Large community"],
      cons: ["Plugin management","Can be heavy if misconfigured"],
      official_url: "https://wordpress.org",
      case_studies: [{title:"Editorial site", summary:"News portals use WP for editorial workflows.", link:"#"}],
      last_updated: "2025-11-11"
    },
    {
      id: "figma",
      name: "Figma",
      category: "Design & Prototyping",
      short_description: "Cloud-based UI design and prototyping with real-time collaboration.",
      long_description: "Figma allows teams to co-edit designs, build component libraries, and hand off specs to developers.",
      tags: ["design","collaboration","prototyping"],
      skill_level: "beginner",
      pricing_model: "freemium",
      starts_at: "Free / Paid plans",
      integrations: ["FigJam","Plugins"],
      pros: ["Real-time co-editing","Design system components"],
      cons: ["Needs internet","Limited offline mode"],
      official_url: "https://figma.com",
      case_studies: [{title:"Design ops", summary:"Teams use Figma for component libraries.", link:"#"}],
      last_updated: "2025-11-11"
    },
    {
      id: "react",
      name: "React",
      category: "Frontend Framework",
      short_description: "Component-based JavaScript library for interactive UIs.",
      long_description: "React powers fast single-page applications using reusable components and virtual DOM rendering.",
      tags: ["javascript","framework","spa"],
      skill_level: "advanced",
      pricing_model: "free",
      starts_at: "Free",
      integrations: ["Next.js","Vercel"],
      pros: ["Reusable components","Large ecosystem"],
      cons: ["Steep learning curve for beginners"],
      official_url: "https://reactjs.org",
      case_studies: [{title:"Large news site", summary:"Content portals use React components.", link:"#"}],
      last_updated: "2025-11-11"
    },
    {
      id: "vscode",
      name: "Visual Studio Code",
      category: "Code Editor",
      short_description: "Lightweight, extensible code editor with debugging and Git integration.",
      long_description: "VS Code is a developer favorite due to extensibility, speed, and tools like Live Share for collaboration.",
      tags: ["editor","ide","extensions"],
      skill_level: "advanced",
      pricing_model: "free",
      starts_at: "Free",
      integrations: ["Git","Extensions"],
      pros: ["Huge extension marketplace","Live Share"],
      cons: ["Add-ons needed for specific workflows"],
      official_url: "https://code.visualstudio.com",
      case_studies: [{title:"Dev workflows", summary:"Used by dev teams day-to-day.", link:"#"}],
      last_updated: "2025-11-11"
    },
    {
      id: "bootstrap",
      name: "Bootstrap",
      category: "CSS Framework",
      short_description: "Responsive grid & components for fast prototyping.",
      long_description: "Bootstrap provides a ready-made grid and UI components for consistent responsive design across devices.",
      tags: ["css","framework","responsive"],
      skill_level: "beginner",
      pricing_model: "free",
      starts_at: "Free",
      integrations: ["npm","CDN"],
      pros: ["Quick prototyping","Cross-browser support"],
      cons: ["Generic look if uncustomized"],
      official_url: "https://getbootstrap.com",
      case_studies: [{title:"Gov sites", summary:"Used by many public sector sites for quick launch.", link:"#"}],
      last_updated: "2025-11-11"
    },
    {
      id: "tailwind",
      name: "Tailwind CSS",
      category: "Utility CSS",
      short_description: "Utility-first CSS framework enabling custom designs rapidly.",
      long_description: "Tailwind lets you build unique UIs using utility classes rather than pre-styled components.",
      tags: ["css","utility","customizable"],
      skill_level: "intermediate",
      pricing_model: "free",
      starts_at: "Free",
      integrations: ["React","Vue"],
      pros: ["Highly customizable","Small final CSS with purge"],
      cons: ["Verbose HTML classes"],
      official_url: "https://tailwindcss.com",
      case_studies: [{title:"Startup UI", summary:"Used for custom landing pages.", link:"#"}],
      last_updated: "2025-11-11"
    }
  ];
  